/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as JoinInviteCodeRouteImport } from './routes/join/$inviteCode'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers/$customerId'
import { Route as AuthenticatedCustomersNewRouteImport } from './routes/_authenticated/customers/new'
import { Route as AuthenticatedProvidersIndexRouteImport } from './routes/_authenticated/providers/index'
import { Route as AuthenticatedProvidersProviderIdRouteImport } from './routes/_authenticated/providers/$providerId'
import { Route as AuthenticatedProvidersNewRouteImport } from './routes/_authenticated/providers/new'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedServicesServiceIdRouteImport } from './routes/_authenticated/services/$serviceId'
import { Route as AuthenticatedServicesNewRouteImport } from './routes/_authenticated/services/new'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersNewRoute =
  AuthenticatedCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProvidersIndexRoute =
  AuthenticatedProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProvidersProviderIdRoute =
  AuthenticatedProvidersProviderIdRouteImport.update({
    id: '/providers/$providerId',
    path: '/providers/$providerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProvidersNewRoute =
  AuthenticatedProvidersNewRouteImport.update({
    id: '/providers/new',
    path: '/providers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesServiceIdRoute =
  AuthenticatedServicesServiceIdRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesNewRoute =
  AuthenticatedServicesNewRouteImport.update({
    id: '/services/new',
    path: '/services/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/providers/$providerId': typeof AuthenticatedProvidersProviderIdRoute
  '/providers/new': typeof AuthenticatedProvidersNewRoute
  '/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/services/new': typeof AuthenticatedServicesNewRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/providers/': typeof AuthenticatedProvidersIndexRoute
  '/services/': typeof AuthenticatedServicesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/providers/$providerId': typeof AuthenticatedProvidersProviderIdRoute
  '/providers/new': typeof AuthenticatedProvidersNewRoute
  '/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/services/new': typeof AuthenticatedServicesNewRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/providers': typeof AuthenticatedProvidersIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/customers/new': typeof AuthenticatedCustomersNewRoute
  '/_authenticated/providers/$providerId': typeof AuthenticatedProvidersProviderIdRoute
  '/_authenticated/providers/new': typeof AuthenticatedProvidersNewRoute
  '/_authenticated/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/_authenticated/services/new': typeof AuthenticatedServicesNewRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/providers/': typeof AuthenticatedProvidersIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/workspace'
    | '/join/$inviteCode'
    | '/customers/$customerId'
    | '/customers/new'
    | '/providers/$providerId'
    | '/providers/new'
    | '/services/$serviceId'
    | '/services/new'
    | '/customers/'
    | '/providers/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/workspace'
    | '/join/$inviteCode'
    | '/'
    | '/customers/$customerId'
    | '/customers/new'
    | '/providers/$providerId'
    | '/providers/new'
    | '/services/$serviceId'
    | '/services/new'
    | '/customers'
    | '/providers'
    | '/services'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/workspace'
    | '/join/$inviteCode'
    | '/_authenticated/'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/customers/new'
    | '/_authenticated/providers/$providerId'
    | '/_authenticated/providers/new'
    | '/_authenticated/services/$serviceId'
    | '/_authenticated/services/new'
    | '/_authenticated/customers/'
    | '/_authenticated/providers/'
    | '/_authenticated/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/new': {
      id: '/_authenticated/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthenticatedCustomersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/providers/': {
      id: '/_authenticated/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthenticatedProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/providers/$providerId': {
      id: '/_authenticated/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof AuthenticatedProvidersProviderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/providers/new': {
      id: '/_authenticated/providers/new'
      path: '/providers/new'
      fullPath: '/providers/new'
      preLoaderRoute: typeof AuthenticatedProvidersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/$serviceId': {
      id: '/_authenticated/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof AuthenticatedServicesServiceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/new': {
      id: '/_authenticated/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof AuthenticatedServicesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedCustomersNewRoute: typeof AuthenticatedCustomersNewRoute
  AuthenticatedProvidersProviderIdRoute: typeof AuthenticatedProvidersProviderIdRoute
  AuthenticatedProvidersNewRoute: typeof AuthenticatedProvidersNewRoute
  AuthenticatedServicesServiceIdRoute: typeof AuthenticatedServicesServiceIdRoute
  AuthenticatedServicesNewRoute: typeof AuthenticatedServicesNewRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedProvidersIndexRoute: typeof AuthenticatedProvidersIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedCustomersNewRoute: AuthenticatedCustomersNewRoute,
  AuthenticatedProvidersProviderIdRoute: AuthenticatedProvidersProviderIdRoute,
  AuthenticatedProvidersNewRoute: AuthenticatedProvidersNewRoute,
  AuthenticatedServicesServiceIdRoute: AuthenticatedServicesServiceIdRoute,
  AuthenticatedServicesNewRoute: AuthenticatedServicesNewRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedProvidersIndexRoute: AuthenticatedProvidersIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
